### ISSUE TITLE
"claim" produces 502 Bad gateway

### ISSUE THREAD

**Issue by fuglede** [shamblesides/turfwar#9]
If I go to http://ipv4.games/claim?name=watevs, I get this one:

![image](https://user-images.githubusercontent.com/6169306/192085525-65502785-f10d-48ef-9e86-7939ad95ed5e.png)

**Comment by shamblesides** [comment]
Unfortunately It's been a battle keeping the server up against increasingly large DDOS attacks so /claim is disabled until we have time to work on it again.

I think that SQLite may be the chokepoint right now, since a process must acquire an exclusive write lock each time an address claim is made. There's probably a better way to do this.

**Comment by fuglede** [comment]
Ouch, as in a nefarious attack, or just people playing the game?

**Comment by shamblesides** [comment]
I think it was nefarious; they were hitting the /claim route from the same addresses with a bunch of different names with random characters so I can only assume they were trying to overwhelm the server intentionally

**Comment by serialame** [comment]
> I think it was nefarious; they were hitting the /claim route from the same addresses with a bunch of different names with random characters so I can only assume they were trying to overwhelm the server intentionally

i can provide you with larger servers and stuff if you need ^^, i would love to help out where i can

**Comment by shamblesides** [comment]
> i can provide you with larger servers and stuff if you need ^^, i would love to help out where i can

I appreciate it!! I'll let you know, for now I do have it back up and we'll see how it goes from here!
